### ISSUE TITLE
Harvester only - cannot start

### ISSUE THREAD

**Issue by NicodemPL** [Chia-Network/chia-docker#26]
Hi
followed all steps from official wiki - all goes well until I start chia harvester.
Got error and this comes live in logs (below).
Any idea what is wrong? Is this possible that its an error because I am starting this at old 32bit QNAP with Unraid?
Want only to share files from this machine, not via SMB but in "proper" way.

LOGS:

2021-04-27T14:37:37.303 daemon chia.daemon.server         : ERROR    problem starting chia_harvester
Traceback (most recent call last):
  File "/chia-blockchain/chia/daemon/server.py", line 610, in start_service
    process, pid_path = launch_service(self.root_path, exe_command)
  File "/chia-blockchain/chia/daemon/server.py", line 766, in launch_service
    process = subprocess.Popen(
  File "/usr/lib/python3.8/subprocess.py", line 854, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.8/subprocess.py", line 1702, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'chia_harvester'

**Comment by justinengland** [comment]
github issues is not for tech support. please check out keybase for support requests!

**Comment by NicodemPL** [comment]
This is NOT a problem of support with Chia, its an issue with this docker only. It just does not start properly harvester only mode.
try it...
