### ISSUE TITLE
Problem with starting farming

### ISSUE THREAD

**Issue by norbul** [Chia-Network/chia-docker#8]
Full node does not start in docker

I start docker using command
`docker run -p 8444:8444 -p 8555:8555 -v /mnt/chia/plots:/plots --name chia_plots -d ghcr.io/chia-network/chia:latest
`
And get an error:

```
chia start farmer
Daemon not started yet
Starting daemon
Traceback (most recent call last):
  File "/chia-blockchain/venv/bin/chia", line 33, in <module>
    sys.exit(load_entry_point('chia-blockchain', 'console_scripts', 'chia')())
  File "/chia-blockchain/src/cmds/chia.py", line 59, in main
    cli()  # pylint: disable=no-value-for-parameter
  File "/chia-blockchain/venv/lib/python3.8/site-packages/click/core.py", line 1026, in __call__
    return self.main(*args, **kwargs)
  File "/chia-blockchain/venv/lib/python3.8/site-packages/click/core.py", line 956, in main
    rv = self.invoke(ctx)
  File "/chia-blockchain/venv/lib/python3.8/site-packages/click/core.py", line 1518, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/chia-blockchain/venv/lib/python3.8/site-packages/click/core.py", line 1280, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/chia-blockchain/venv/lib/python3.8/site-packages/click/core.py", line 711, in invoke
    return callback(*args, **kwargs)
  File "/chia-blockchain/venv/lib/python3.8/site-packages/click/decorators.py", line 22, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/chia-blockchain/src/cmds/chia.py", line 43, in run_daemon_cmd
    asyncio.get_event_loop().run_until_complete(async_run_daemon(ctx.obj["root_path"]))
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/chia-blockchain/src/daemon/server.py", line 985, in async_run_daemon
    await ws_server.start()
  File "/chia-blockchain/src/daemon/server.py", line 142, in start
    self.websocket_server = await serve(
  File "/chia-blockchain/venv/lib/python3.8/site-packages/websockets/server.py", line 965, in __await_impl__
    server = await self._create_server()
  File "/usr/lib/python3.8/asyncio/base_events.py", line 1463, in create_server
    raise OSError(err.errno, 'error while attempting '
OSError: [Errno 99] error while attempting to bind on address ('::1', 55400, 0, 0): cannot assign requested address
Daemon not started yet
Failed to create the chia daemon
```

**Comment by norbul** [comment]
Editing entrypoint.sh and replaced testnet to mainnet solved problem
